import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Pane, Heading, TextInput, Button } from 'evergreen-ui'
import { Canvas } from '../components/Canvas'

const Home: NextPage = () => {
    const [whiteboardInput, setWhiteboardInput] = useState('')
    const [whiteboardId, setWhiteboardId] = useState<undefined | string>(undefined)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Pane display='flex' alignItems='center' justifyContent='center' flexDirection='column'>
            <Pane flex={1}>
                <Heading size={900}>Serverless Whiteboard</Heading>
                <Heading size={500}>Includes auto-saving and real-time collaboration</Heading>
            </Pane>

            <Pane flex={1}>
                {
                    whiteboardId
                        ? <Canvas whiteboardId={whiteboardId} />
                        : <>
                            <TextInput onChange={(e: Event) => setWhiteboardInput((e.target as HTMLInputElement).value)} value={whiteboardInput} placeholder="Whiteboard ID" />
                            <Button onClick={() => {setWhiteboardId(whiteboardInput)}}>Submit</Button>
                        </>
                }
            </Pane>
        </Pane>

      </main>
    </div>
  )
}

export default Home
